version: '3'

services:
  laravel-db:
    container_name: ${CONTAINER_DB_NAME}
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ${DB_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  laravel-php:
    depends_on:
      - laravel-db
    container_name: ${CONTAINER_LARAVEL_NAME}
#    image: httpd:alpine
#    image: php
    build:
      context: ./
    restart: unless-stopped
    volumes:
      - ${LARAVEL_APP}:/app/
      - ${LARAVEL_CORE}:/var/www/
      - ${LARAVEL_PUBLIC}:/var/www/html/
      - ${LARAVEL_STORAGE}:/var/www/storage/
      - ${LARAVEL_ENV_FILE}:/var/www/.env:ro
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
   default:
     external:
       name: ${NETWORK}
